
const state = {
  enemyAttack: 3,
  enemyHp: 25,
  enemyNameFirst: '',
  enemyNamesFirst: [
    'Dr.',
    'Greasus',
    'Roy',
    'Cutthroat',
    'Hans',
    'Norman',
    'Peter',
    'Ol\'',
    'Tommy',
    'Vince',
  ],
  enemyNameLast: '',
  enemyNamesLast: [
    'Butttooth',
    'Cane',
    'Dirty',
    'Goldtooth',
    'Gruber',
    'Lynx',
    'Heliot',
    'the Descpicable',
    'the Wretched',
  ],
  enemyBasicWeapon: '',
  enemyBasicWeapons: [
    'Fork',
    'Butcher\'s knife',
    'Knife',
    'Dagger',
    'Bare fist',
    'Spoon',
    'Stick',
  ],
  enemyBasicWeaponMaterial: '',
  enemyBasicWeaponMaterials: [
    'Silver',
    'Steel',
    'Iron',
    'Wooden',
  ],
  enemyBasicWeaponQuality: '',
  enemyBasicWeaponQualitys: [
    'Chipped',
    'Flawed',
    'Normal',
    'Rusty',
    'Perfect',
    'Pristine',
    'Superb',
    'Exemplary',
    'Exceptional',
    'Legendary',
    'Royal',
    'Imperial',
    'Polished',
    'Wonderful',
    'Imperfect',
    'Common',
    'Regular',
    'Rare',
    'Uncommon',
    'Mediocre',
    'Shabby',
    'Flawless',
    'Enhanced',
    'Dwarven',
    'Dragonbone',
  ],
  enemyWeaponSize: '',
  enemyWeaponSizes: [
    'Miniature',
    'Majestic',
    'Puny',
    'Tiny',
    'Huge',
    'Small',
    'Large',
    'Giant',
    'Gigantic',
  ],
};

export default {
  state,
};
