
const state = {
  enemyAttack: 3,
  enemyHp: 25,
  enemyNameFirst: '',
  enemyNamesFirst: [
    'Dr.',
    'Greasus',
    'Roy',
    'Cutthroat',
    'Hans',
    'Norman',
    'Peter',
    'Ol\'',
    'Tommy',
    'Vince',
  ],
  enemyNameLast: '',
  enemyNamesLast: [
    'Butttooth',
    'Cane',
    'Dirty',
    'Goldtooth',
    'Gruber',
    'Lynx',
    'Heliot',
    'the Descpicable',
    'the Wretched',
  ],
  enemyBasicWeapon: '',
  enemyBasicWeapons: [
    'Fork',
    'Butcher\'s knife',
    'Knife',
    'Dagger',
    'Bare fists',
    'Spoon',
    'Stick',
  ],
  enemyBasicWeaponMaterial: '',
  enemyBasicWeaponMaterials: [
    'silver',
    'steel',
    'iron',
    'wooden',
  ],
  enemyBasicWeaponQuality: '',
  enemyBasicWeaponQualitys: [
    'chipped',
    'flawed',
    'normal',
    'rusty',
    'perfect',
    'pristine',
    'superb',
    'exemplary',
    'exceptional',
    'legendary',
    'royal',
    'imperial',
    'polished',
    'wonderful',
    'imperfect',
    'common',
    'regular',
    'rare',
    'uncommon',
    'mediocre',
    'shabby',
    'flawless',
    'enhanced',
    'dwarven',
    'dragonbone',
  ],
  enemyWeaponSize: '',
  enemyWeaponSizes: [
    'miniature',
    'majestic',
    'puny',
    'tiny',
    'huge',
    'small',
    'large',
    'giant',
    'gigantic',
    'great',
  ],
};

export default {
  state,
};
