
const state = {
  age: '',
  alignment: '',
  alignments: [
    'chaotic good',
    'good',
    'evil',
    'chaotic evil',
    'psychopath',
  ],
  animalName: '',
  animalNames: [
    'Basil',
    'Charlie',
    'Frank',
    'Fred',
    'Gertrude',
    'Bruce',
    'Lucelle',
  ],
  animalType: '',
  animalTypes: [
    'Bat',
    'Bird',
    'Cat',
    'Dog',
    'Eagle',
    'Sloth',
    'Lizard',
    'Monkey',
    'Mouse',
    'Raven',
    'Rat',
    'Salamander',
    'Snake',
    'Turtle',
    'Fish',
    'Frog',
    'Tiger',
    'Horse',
  ],
  appearance: '',
  appearances: [
    'Beautiful',
    'Butt Ugly',
    'Handsome',
  ],
  armour: '',
  armours: [
    'adamantine',
    'toad leather',
    'bare skin',
  ],
  gender: '',
  genders: [
    'male',
    'female',
    'transsexual',
    'transvestite',
    'genderqueer',
    'androgyne',
    'bigender',
    'drag king',
    'drag queen',
  ],
  location: '',
  locations: [
    'Dicklesberry',
    'Another Dimension',
    'Hell',
    'Brobdingnag',
  ],
  mood: '',
  moods: [
    'Angry',
    'Calm',
    'Chaotic',
    'Cranky',
    'Depressed',
    'Inebrieated',
    'Lonely',
    'Happy',
    'Grumpy',
    'Mischievous',
    'Melancholy',
    'Pissed off',
    'Sad',
  ],
  nameFirst: '',
  namesFirst: [
    'Basil',
    'Herbert',
    'Winston',
    'Frederick',
    'Grumpf',
    'Maximillion',
    'Wilhelm',
    'Theodore',
    'Greasus',
  ],
  nameMiddle: '',
  namesMiddle: [
    'Berrybrook',
    'Deathrump',
    'Wellington',
    'the Great',
    'Bloodlord',
    'Helldoom',
    'Firerump',
    'Flamebeard',
    'the Flatulant IV',
    'Thornheart',
    'Ragefist',
    'Goldtooth',
    'Guillemaere',
    'Schwarzmüller',
  ],
  nameLast: '',
  namesLast: [
    'Berrybrook',
    'Deathrump',
    'Wellington',
    'the Great',
    'Bloodlord',
    'Helldoom',
    'Firerump',
    'Flamebeard',
    'the Flatulant IV',
    'Thornheart',
    'Ragefist',
    'Goldtooth',
    'Guillemaere',
    'Schwarzmüller',
  ],
  occupation: '',
  occupations: [
    'Knight',
    'Sorcerer',
    'Peasent',
    'Noble',
    'Paladin',
    'Ninja',
    'Thief',
    'Warlord',
    'Wizard',
  ],
  race: '',
  races: [
    'Hobbit',
    'Ork',
    'Pixie',
    'Owlbear',
    'Satyr',
    'Lizardman',
    'Goblin',
    'Monopod',
    'Hobgoblin',
    'Giant',
    'Undead',
    'Human',
    'Dwarf',
    'Gnome',
    'Elf',
    'Ogre',
    'Halfling',
    'Half-Ork',
    'Half-Elf',
    'Ghost',
    'Half-Ogre',
    'Half-Giant',
    'Vampire',
  ],
  title: '',
  titles: [
    'Mr',
    'Mrs',
    'King',
    'Prince',
    'Sir',
    'Dame',
  ],
  speedType: '',
  speedTypes: [
    'very slow',
    'very fast',
  ],
  strengthType: '',
  strengthTypes: [
    'very strong',
    'very weak',
  ],
  weapon: '',
  weapons: [
    'The Sceptre of Titans',
    'The Sword of Couronne',
  ],
  weaponBasic: '',
  weaponBasics: [
    'large fork',
    'Butcher\'s knife',
    'knife',
    'tiny dagger',
    'bare fists',
  ],
  size: '',
  sizes: [
    'tiny',
    'small',
    'large',
    'gigantic',
  ],
};

export default {
  state,
};
